-- V9: Seed Initial Botanical Products into PostgreSQL
INSERT INTO products (
    id, title, subtitle, slug, category_id, price, original_price, weight_grams,
    stock_quantity, image_url, badge, rating, review_count, scent_profile,
    ingredients, skin_type, description, is_active
) VALUES
(
    'b0000000-0000-0000-0000-000000000001',
    'Woodland Herbal Bar',
    'Rustic Oat & Shea Butter Bar',
    'woodland-herbal-bar',
    (SELECT id FROM categories WHERE slug = 'botanical-herbal' LIMIT 1),
    349.00,
    399.00,
    200,
    100,
    '/images/Natural_Soap_And_Bath_Bomb.webp',
    'Herbal Soap',
    5.0,
    42,
    'Dried Wildflowers, Oat Milk, Essential Oils',
    'Oat Milk, Shea Butter, Coconut Oil, Dried Wildflowers, Essential Oil Blend',
    'Normal to dry skin',
    'A rustic oat-and-shea bar finished with dried wildflowers for a calm, grounding wash.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000002',
    'Aloe & Mint Refresh',
    'Cooling Aloe & Fresh Mint Leaf',
    'aloe-mint-refresh',
    (SELECT id FROM categories WHERE slug = 'botanical-herbal' LIMIT 1),
    299.00,
    349.00,
    200,
    100,
    '/images/soap_3.jpg',
    'Herbal Soap',
    4.5,
    37,
    'Peppermint Essential Oil, Fresh Mint, Aloe',
    'Aloe Vera, Mint Leaf, Coconut Oil, Glycerin, Peppermint Essential Oil',
    'All skin types',
    'A cooling aloe vera bar with fresh mint leaf, perfect for a refreshing morning wash.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000003',
    'Lavender & Rose Garden Set',
    '5-Bar Artisan Botanical Collection',
    'lavender-rose-garden-set',
    (SELECT id FROM categories WHERE slug = 'floral-rose' LIMIT 1),
    599.00,
    699.00,
    200,
    100,
    '/images/soap_2.jpg',
    'Floral Soap',
    5.0,
    64,
    'Lavender Buds, Rose Petals, Honey Citrus, Green Tea',
    'Lavender Buds, Rose Petals, Citrus Zest, Green Tea, Shea Butter',
    'Normal skin',
    'A five-bar collection featuring lavender, honey citrus, exfoliating green tea and rose petal.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000004',
    'Daisy Bloom Bar',
    'Hand-Molded Daisy Floral Bar',
    'daisy-bloom-bar',
    (SELECT id FROM categories WHERE slug = 'floral-rose' LIMIT 1),
    279.00,
    320.00,
    200,
    100,
    '/images/soap_14.jpg',
    'Floral Soap',
    4.5,
    21,
    'Chamomile Extract, Soft Daisy Blossom',
    'Glycerin Base, Chamomile Extract, Fragrance Oil, Botanical Colorant',
    'Normal skin',
    'Hand-molded daisy soaps with a soft floral scent, sweet enough to double as a bathroom accent.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000005',
    'Rose Petal Trio',
    'Hand-Carved Ribbon Roses',
    'rose-petal-trio',
    (SELECT id FROM categories WHERE slug = 'floral-rose' LIMIT 1),
    399.00,
    450.00,
    200,
    100,
    '/images/soap_8.jpg',
    'Floral Soap · Gift',
    5.0,
    29,
    'Pure Rose Oil, Natural Damask Rose',
    'Glycerin Base, Rose Fragrance Oil, Natural Colorant',
    'Normal skin',
    'Three hand-carved rose soaps tied with ribbon — a romantic, gift-ready favourite.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000006',
    'Oatmeal & Honey Bar',
    'Raw Honey & Ground Oats Layered Bar',
    'oatmeal-honey-bar',
    (SELECT id FROM categories WHERE slug = 'nourishing-honey' LIMIT 1),
    329.00,
    379.00,
    200,
    100,
    '/images/soap_6.jpg',
    'Honey & Natural',
    5.0,
    58,
    'Raw Forest Honey, Golden Oats, Warm Vanilla',
    'Raw Honey, Ground Oats, Goat''s Milk, Coconut Oil',
    'Normal to dry skin',
    'A cozy, golden bar layered with real oats and a drizzle of honey for a comforting soak.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000007',
    'Green Grape Cluster Soap',
    'Hand-Molded Grape Seed Glycerin Bar',
    'green-grape-cluster-soap',
    (SELECT id FROM categories WHERE slug = 'nourishing-honey' LIMIT 1),
    349.00,
    399.00,
    200,
    100,
    '/images/soap_7.jpg',
    'Honey & Natural',
    4.5,
    18,
    'Grape Seed Extract, Light Crisp Fruit',
    'Glycerin Base, Grape Seed Extract, Fragrance Oil',
    'Normal skin',
    'A playful hand-molded grape cluster bar with a light, fruity fragrance.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000008',
    'Sea Mint Massage Bar',
    'Textured Nub Exfoliating Bar',
    'sea-mint-massage-bar',
    (SELECT id FROM categories WHERE slug = 'exfoliating-purifying' LIMIT 1),
    379.00,
    429.00,
    200,
    100,
    '/images/soap_5.jpg',
    'Moisturizing',
    4.5,
    15,
    'Sea Salt, Peppermint Essential Oil, Shea',
    'Shea Butter, Coconut Oil, Sea Salt, Peppermint Essential Oil',
    'Normal to oily skin',
    'A textured massage bar with raised nubs to gently buff while you wash.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000009',
    'Wildflower Glycerin Bar',
    'Real Pressed Suspended Wildflowers',
    'wildflower-glycerin-bar',
    (SELECT id FROM categories WHERE slug = 'gift-sets' LIMIT 1),
    449.00,
    499.00,
    200,
    100,
    '/images/soap_4.jpg',
    'Special Edition',
    5.0,
    33,
    'Pressed Botanical Petals, Vitamin E',
    'Glycerin Base, Pressed Wildflowers, Vitamin E',
    'Normal skin',
    'Crystal-clear glycerin soap with real pressed wildflowers suspended inside — a true statement piece.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000010',
    'Ocean Bliss Sliding Box Soap Trio',
    'Terrazzo Stone Soap & Keepsake Box',
    'ocean-bliss-sliding-box-soap-trio',
    (SELECT id FROM categories WHERE slug = 'gift-sets' LIMIT 1),
    699.00,
    799.00,
    200,
    100,
    '/images/ocean_bliss_trio.jpg',
    'Artisan Gift Set',
    5.0,
    38,
    'Ocean Breeze, Marine Botanicals, Sea Clay',
    'Organic Coconut Oil, Pure Shea Butter, Sea Clay, Marine Botanical Extracts, Natural Mineral Terrazzo Inclusions, Ocean Breeze & Mint Essential Oils',
    'All skin types',
    'A set of three arched sliding keepsake drawer boxes featuring handcrafted terrazzo stone soaps with delicate seashell, coral, and seaweed botanical illustrations.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000011',
    'Little Explorers Animal Set',
    'Animal-Shaped Gentle Soap Collection',
    'little-explorers-animal-set',
    (SELECT id FROM categories WHERE slug = 'gift-sets' LIMIT 1),
    399.00,
    450.00,
    200,
    100,
    '/images/soap_11.jpg',
    'Special · Kids',
    4.5,
    24,
    'Mild Coconut, Gentle Sweet Essence',
    'Glycerin Base, Coconut Oil, Mild Fragrance Oil',
    'All skin types',
    'A cheerful set of animal-shaped soaps designed to make bath time a little more fun.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000012',
    'Herbarium Pressed Botanical Bar',
    'Encased Viola Pansies & Rosemary',
    'herbarium-pressed-botanical-bar',
    (SELECT id FROM categories WHERE slug = 'floral-rose' LIMIT 1),
    469.00,
    520.00,
    200,
    100,
    '/images/soap_20.jpg',
    'Artisan Floral',
    5.0,
    38,
    'Pure Lavender Oil, Rosemary, Pressed Viola',
    'Glycerin Base, Pressed Viola Pansies, Rosemary Sprigs, Vitamin E, Pure Lavender Oil',
    'All skin types',
    'Handcrafted crystal-clear botanical soaps encasing real pressed pansies and fragrant herbs in glass-like clarity.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000013',
    'Relax & Enjoy Spa Ritual Box',
    'Honeycomb Bar, Bath Salt & Sisal Crate',
    'relax-enjoy-spa-ritual-box',
    (SELECT id FROM categories WHERE slug = 'gift-sets' LIMIT 1),
    899.00,
    999.00,
    200,
    100,
    '/images/soap_21.jpg',
    'Deluxe Gift Box',
    5.0,
    52,
    'Wild Honey, Rose Petal, Himalayan Salt',
    'Raw Wild Honey, Goat''s Milk, Himalayan Pink Bath Salt, Rose Essential Oil, Shea Butter',
    'Dry, sensitive & normal skin',
    'A luxurious self-care crate featuring honeybee honeycomb soap, carved rose & daisy bars, botanical bath crystals, waffle towel, and natural sisal sponge.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000014',
    'Ocean Breeze Sea Turtle Gift Box',
    'Aquamarine Sea Turtle & Seashell Soaps',
    'ocean-breeze-sea-turtle-gift-box',
    (SELECT id FROM categories WHERE slug = 'gift-sets' LIMIT 1),
    799.00,
    899.00,
    200,
    100,
    '/images/soap_22.jpg',
    'Curated Gift Box',
    5.0,
    44,
    'Marine Botanical Fragrance, Coconut Sea Minerals',
    'Organic Coconut Oil, Sea Salt Minerals, Shea Butter Base, Marine Botanical Fragrance, Plant Mica',
    'All skin types',
    'A charming coastal gift set featuring an aquamarine sea turtle soap nestled with pastel artisan seashells and tied with natural jute twine.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000015',
    'Ocean Seashore Crystal Wave Bar',
    'Deep Teal Swirling Sea Foam & Starfish',
    'ocean-seashore-crystal-wave-bar',
    (SELECT id FROM categories WHERE slug = 'exfoliating-purifying' LIMIT 1),
    429.00,
    489.00,
    200,
    100,
    '/images/soap_23.jpg',
    'Special Edition',
    4.5,
    31,
    'Sea Kelp Extract, Ocean Breeze Oils',
    'Plant Glycerin, Epsom Salt & Sea Minerals, Sea Kelp Extract, Ocean Breeze Essential Oils',
    'Normal to oily skin',
    'Deep ocean teal glycerin soap bars poured with swirling sea foam, embedded shells, and a golden starfish.',
    TRUE
),
(
    'b0000000-0000-0000-0000-000000000016',
    'Rustic Artisan Favor & Dish Set',
    'Cold-Processed Bar + Wooden Tray + Sisal',
    'rustic-artisan-favor-dish-set',
    (SELECT id FROM categories WHERE slug = 'botanical-herbal' LIMIT 1),
    549.00,
    599.00,
    200,
    100,
    '/images/soap_24.jpg',
    'Artisan Set',
    5.0,
    49,
    'Cedar & Amber Essential Oils, Raw Shea',
    'Olive Oil, Castor Oil, Oat Extract, Cedar & Amber Essential Oils, Raw Shea Butter',
    'All skin types',
    'Cold-processed handmade soap bar in an organza keepsake pouch with a slotted wooden drainage tray and natural sisal scrub pad.',
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    slug = EXCLUDED.slug,
    category_id = EXCLUDED.category_id,
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price,
    weight_grams = EXCLUDED.weight_grams,
    stock_quantity = EXCLUDED.stock_quantity,
    image_url = EXCLUDED.image_url,
    badge = EXCLUDED.badge,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    scent_profile = EXCLUDED.scent_profile,
    ingredients = EXCLUDED.ingredients,
    skin_type = EXCLUDED.skin_type,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP;
